# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 06:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsprofile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 6, 53, 42, 151998, tzinfo=utc)),
        ),
    ]
