# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 10:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160911_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprof',
            name='heigth_field',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='newsprofile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 10, 14, 30, 185048, tzinfo=utc)),
        ),
    ]
