# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='offtop_comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
