# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160917_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprof',
            options={'ordering': ['-reputation']},
        ),
        migrations.AddField(
            model_name='userprof',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
