# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160917_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_admin', models.TextField(max_length=1000)),
                ('date_message_admin', models.DateField(auto_now=True)),
            ],
        ),
    ]
