# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160819_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offtop_comment',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='about',
            field=models.CharField(default=0, max_length=80, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Заголовок'),
        ),
    ]
