# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 19:46
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160820_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='heigth_field', null=True, upload_to=blog.models.upload_url, verbose_name='Аватарка', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('heigth_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(max_length=40, verbose_name='Описание'),
        ),
    ]
