# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_messageforadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('url', models.URLField()),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 9, 30, 11, 39, 41, 58949, tzinfo=utc))),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprof',
            options={'ordering': ['-reputation', '-user_key']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='heigth_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_post',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
    ]
