# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160930_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesblog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
