# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160826_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='count_likes',
            field=models.IntegerField(default=0),
        ),
    ]
