# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_likes_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='dislike',
        ),
    ]
