# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160826_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
