# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_likes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='count_likes',
            field=models.BooleanField(default=False),
        ),
    ]
