# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160826_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='count_likes',
            new_name='like',
        ),
    ]
