# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_userprof'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprof',
            name='reputation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
