# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userprof_reputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprof',
            name='reputation',
        ),
        migrations.AddField(
            model_name='userprof',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprof',
            name='rank_name',
            field=models.CharField(default='НОУНЕЙМ', max_length=10),
        ),
    ]
