# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20160827_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprof',
            name='rank',
        ),
    ]
