# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 14:14
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_userprof_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprof',
            name='avatar',
            field=models.ImageField(blank=True, height_field='heigth_field', null=True, upload_to=blog.models.upload_url, validators=[blog.models.UserProf.validate_image], verbose_name='Постер', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='userprof',
            name='heigth_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprof',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
