# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20160828_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField()),
                ('vocabulary', models.TextField()),
                ('story', models.TextField()),
                ('cultural_notes', models.TextField()),
                ('action', models.TextField()),
            ],
            options={
                'ordering': ['lesson_number'],
            },
        ),
    ]
