# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20160904_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='communicaton_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
