# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentgame',
            name='comment',
            field=models.TextField(max_length=500, verbose_name='Ваш комментарий:'),
        ),
    ]
