# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_score2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score2048',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
