# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20160910_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentgame',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='commentgame',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
