# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20160910_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentgame',
            options={'ordering': ['-date']},
        ),
    ]
