# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesblog',
            name='url',
        ),
        migrations.AddField(
            model_name='moviesblog',
            name='key_move',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
