# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160930_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesblog',
            name='title',
        ),
        migrations.AlterField(
            model_name='moviesblog',
            name='key_move',
            field=models.CharField(help_text='Возможно вы ввели неправильный ключ', max_length=300, verbose_name='Ключ видео(последние 11 цифр ссылке на ролик)'),
        ),
    ]
