# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_auto_20160930_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForMoveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='moviesblog',
            old_name='key_move',
            new_name='youtube_key',
        ),
        migrations.AddField(
            model_name='commentformoveis',
            name='movie_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MoviesBlog'),
        ),
        migrations.AddField(
            model_name='commentformoveis',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
