# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20161001_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentformoveis',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='moviesblog',
            options={'ordering': ['-date']},
        ),
    ]
